name: test-ci
run-name: "Building from - [ Branch: '${{ github.ref_name }}' ]"
on:
  workflow_dispatch:
    inputs: 
       test:
        type: boolean
        description: 'build'    
        required: false
        default: 'false'                

jobs:
  call-ci-workflow:

    uses: balasharan/citemplatecalling/.github/workflows/ci.yml@main
    with:
      
      TAG: test-${{ github.run_id }}-${{ github.run_number }}
      javaVersion: 17
